DROP TABLE TEMP;

CREATE TABLE TEMP (
ARTICULO NUMBER(5),
MENSAJE VARCHAR2(15)
);

DECLARE

	V_PEDIDO NUMBER:=&PEDIDO;
	V_STOCK NUMBER:=0;
	
BEGIN

	SELECT STOCK INTO V_STOCK FROM ARTICULOS WHERE IDART=V_PEDIDO;
	
	IF (V_STOCK>0) THEN
		INSERT INTO TEMP VALUES (V_PEDIDO,'VENDIDO');
		UPDATE ARTICULOS SET STOCK=STOCK-1 
		WHERE IDART=V_PEDIDO;
		DBMS_OUTPUT.PUT_LINE('Se ha vendido correctamente');
	ELSE 
		DBMS_OUTPUT.PUT_LINE('No hay existencias del producto');
		INSERT INTO TEMP VALUES (V_PEDIDO,'No hay stock');
	END IF;
	
END;
/

SELECT * FROM TEMP;
