CREATE OR REPLACE TYPE VETERINARIO AS OBJECT (
ID INTEGER,
NOMBRE VARCHAR2(100),
DIRECCION VARCHAR2(255)
);
/

CREATE OR REPLACE TYPE MASCOTA AS OBJECT (
ID INTEGER,
RAZA VARCHAR2(100),
NOMBRE VARCHAR2(100),
VET REF VETERINARIO
);
/

DROP TABLE MASCOTAS;
DROP TABLE VETERINARIOS;

CREATE TABLE VETERINARIOS OF VETERINARIO;
INSERT INTO VETERINARIOS VALUES(1,'Jesus perez','Calle el Mareo, 29');

CREATE TABLE MASCOTAS OF MASCOTA;
INSERT INTO MASCOTAS VALUES(1,'Perro','Sprocjet',(SELECT REF(V) FROM VETERINARIOS V WHERE V.ID=1));

SELECT * FROM MASCOTAS;
SELECT ID, NOMBRE, DEREF(VET) FROM MASCOTAS;
SELECT NOMBRE,RAZA,DEREF(M.VET).NOMBRE FROM MASCOTAS M;

DROP TABLE MASCOTAS;
DROP TABLE VETERINARIOS;
DROP TYPE MASCOTA;
DROP TYPE VETERINARIO;


