CLEAR SCR;

DROP TABLE CLIENTES1;
DROP TYPE LISTIN;
DROP TYPE TELEFONO;

CREATE TYPE TELEFONO AS OBJECT (
TIPO VARCHAR2(30),
NUMERO NUMBER
);
/

CREATE TYPE LISTIN AS TABLE OF TELEFONO;
/

CREATE TABLE CLIENTES1 (
ID_CLI NUMBER,
NOMBRE VARCHAR2(30),
APELLIDO VARCHAR2(30),
DIRECCION VARCHAR2(30),
POBLACION VARCHAR2(30),
PROVINCIA VARCHAR2(30),
TELEFONOS LISTIN
)
NESTED TABLE TELEFONOS STORE AS TEL_TAB;

INSERT INTO CLIENTES1 VALUES (1,'EDUARDO','PIEDELOBO','CALLE CAOBA MENOL','MADRID','MADRID',LISTIN(TELEFONO('CELULAR',928372938),
				  TELEFONO('TRABAJO',922374651),
				  TELEFONO('CASA',922374881))
);

INSERT INTO CLIENTES1 VALUES (2,'PEDRO','PIEDELEON','CALLE CACA MENOL','MADRID','MADRID',LISTIN(TELEFONO('CELULAR',928372238),
				  TELEFONO('TRABAJO',966374651),
				  TELEFONO('CASA',921174881))
);

INSERT INTO CLIENTES1 VALUES (3,'PEPE','PIEGATO','CALLE CAJEEA MENOL','MADRID','MADRID',LISTIN(TELEFONO('CELULAR',928378838),
				  TELEFONO('TRABAJO',999374651),
				  TELEFONO('CASA',922377881))
);

SELECT * FROM CLIENTES;

SELECT TYPE_NAME FROM USER_TYPES;

SELECT OBJECT_NAME FROM USER_OBJECTS;

SELECT OBJECT_NAME FROM USER_OBJECTS;

SELECT TEL.NUMERO FROM CLIENTES1 C, TABLE(C.TELEFONOS) TEL WHERE ID_CLI=3;


UPDATE CLIENTES1 SET TELEFONOS=LISTIN(TELEFONO('FIJO',093029392),
				       TELEFONO('MOVIL PERSONAL',02940583),
					TELEFONO('MOVILEMPRESA',029485928)
) WHERE ID_CLI=1;

SELECT TEL.NUMERO FROM CLIENTES1 C, TABLE(C.TELEFONOS) TEL;

SELECT ID_CLI,TEL.TIPO,TEL.NUMERO,NOMBRE FROM CLIENTES1 C, TABLE(C.TELEFONOS) TEL;




