CREATE OR REPLACE TYPE DIRECCION1 AS OBJECT (
CALLE VARCHAR2(20),
CIUDAD VARCHAR2(10),
CODIGO_POST NUMBER(5)
);
/

CREATE OR REPLACE TYPE PERSONA AS OBJECT (
CODIGO NUMBER,
NOMBRE VARCHAR2(10),
DIREC DIRECCION1,
FECHA_NAC DATE
);
/

DECLARE
DIR DIRECCION1:=DIRECCION1(NULL,NULL,NULL);
P PERSONA := PERSONA(NULL,NULL,NULL,NULL);
BEGIN
DIR.CALLE:= 'LA MINA';
DIR.CIUDAD := 'GUADALAJARA';
DIR.CODIGO_POST := '19001';
P.CODIGO := 1;
P.NOMBRE := 'JUAN';
P.DIREC := DIR;
P.FECHA_NAC := '10/11/1988';
END;
/

DROP TABLE ALUMNOS CASCADE CONSTRAINTS;

CREATE TABLE ALUMNOS OF PERSONA(CODIGO PRIMARY KEY);

INSERT INTO ALUMNOS VALUES (1,'El menol klk', DIRECCION1('CALLE RD','SANTO DOMINGO',28030),'10/10/1990');
INSERT INTO ALUMNOS VALUES (2,'Federico', DIRECCION1('Alto San Isidro','GUADALAJARA',28830),'10/10/1980');

SELECT * FROM ALUMNOS;

SELECT * FROM ALUMNOS C WHERE C.DIREC.CIUDAD='GUADALAJARA';
SELECT CODIGO,DIREC FROM ALUMNOS;
UPDATE ALUMNOS C SET C.DIREC.CIUDAD = 'guadalajara' WHERE C.DIREC.CIUDAD='GUADALAJARA';

DECLARE	
	CURSOR C1 IS SELECT NOMBRE,C.DIREC.CIUDAD FROM ALUMNOS C;
	V_NOMBRE VARCHAR2(15);
	V_CALLE VARCHAR2(15);
BEGIN
	OPEN C1;
	FETCH C1 INTO V_NOMBRE,V_CALLE;
	
	WHILE C1%FOUND LOOP 
	
	DBMS_OUTPUT.PUT_LINE('Alumno: '||V_NOMBRE||' - Calle: '||V_CALLE);
	
	FETCH C1 INTO V_NOMBRE,V_CALLE;
	END LOOP;
END;
/
DELETE FROM ALUMNOS C WHERE C.DIREC.CIUDAD='guadalajara';


