CLEAR SCR;
--Creación tablas

DROP TABLE LINEASVENTA;
DROP TABLE VENTAS;
DROP TABLE CLIENTE;
DROP TABLE PRODUCTOS;

CREATE TABLE CLIENTE (
ID_CLIENTE NUMBER(6) PRIMARY KEY,
NOMBRE VARCHAR(20),
DIRECCION VARCHAR2(30),
POBLACION VARCHAR(20),
CP VARCHAR2(20),
PROVINCIA VARCHAR2(20),
NIF VARCHAR2(20),
TELEFONO1 NUMBER(10),
TELEFONO2 NUMBER(10),
TELEFONO3 NUMBER(10)
);

CREATE TABLE PRODUCTOS(
ID_PRODUCTO NUMBER(6) PRIMARY KEY,
DESCRIPCION VARCHAR2(30),
PVP NUMBER(9),
STOCK_ACTUAL NUMBER(9)
);

CREATE TABLE VENTAS (
ID_VENTAS NUMBER(6),
ID_CLIENTE NUMBER(6),
FECHA_VENTA DATE,
CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE LINEASVENTA (
ID_VENTA NUMBER(6),
NUMERO_LINEA NUMBER(6),
ID_PRODUCTO VARCHAR2(6),
CANTIDAD NUMBER(9),
CONSTRAINT PK_VENTA_NUMEROLINEA PRIMARY KEY (ID_VENTA,NUMERO_LINEA),
CONSTRAINT FK_NUMERO_LINEA FOREIGN KEY (NUMERO_LINEA)
	REFERENCES PRODUCTOS(ID_PRODUCTO)
);


--Diseño modelo objeto - relacional

DROP TABLE TABLA_VENTAS;
DROP TABLE TABLA_PRODUCTOS;
DROP TABLE TABLA_CLIENTES;
DROP TYPE TIP_VENTA;
DROP TYPE TIP_LINEAS_VENTA;
DROP TYPE TIP_LINEA_VENTA;
DROP TYPE TIP_PRODUCTO;
DROP TYPE TIP_CLIENTE;
DROP TYPE TIP_DIRECCION;
DROP TYPE TIP_TELEFONOS;

CREATE TYPE TIP_TELEFONOS AS VARRAY(3) OF VARCHAR2(15);
/

CREATE TYPE TIP_DIRECCION AS OBJECT (
CALLE VARCHAR2(50),
POBLACION VARCHAR2(50),
COD_POS VARCHAR2(20),
PROVINCIA VARCHAR2(40)
);
/

CREATE TYPE TIP_CLIENTE AS OBJECT (
ID_CLIENTE NUMBER(6),
NOMBRE VARCHAR2(50),
DIREC TIP_DIRECCION,
NIF VARCHAR2(9),
TELEF TIP_TELEFONOS
);
/

CREATE TYPE TIP_PRODUCTO AS OBJECT (
ID_PRODUCTO NUMBER(6),
DESCRIPCION VARCHAR2(80),
PVP NUMBER(9),
STOCK_ACTUAL NUMBER(9)
);
/

CREATE TYPE TIP_LINEA_VENTA AS OBJECT (
NUMERO_LINEA NUMBER(9),
ID_PRODUCTO REF TIP_PRODUCTO,
CANTIDAD NUMBER(9)
);
/

--CREACION DE TABLAS OBJETO - TYPES
CLEAR SCR;

CREATE TYPE TIP_LINEAS_VENTA AS TABLE OF TIP_LINEA_VENTA;
/

CREATE TYPE TIP_VENTA AS OBJECT (
ID_VENTA NUMBER(6),
ID_CLIENTE REF TIP_CLIENTE,
FECHA_VENTA DATE,
LINEAS TIP_LINEAS_VENTA,
MEMBER FUNCTION TOTAL_VENTA RETURN NUMBER
)
/

CREATE OR REPLACE TYPE BODY TIP_VENTA AS 
MEMBER FUNCTION TOTAL_VENTA RETURN NUMBER IS

	TOTAL NUMBER:=0;
	LINEA TIP_LINEA_VENTA;
	PRODUCTO TIP_PRODUCTO;	
		
BEGIN
	
	FOR I IN 1..LINEAS.COUNT LOOP
		LINEA:=LINEAS(I);
		SELECT DEREF(LINEA.ID_PRODUCTO) INTO PRODUCTO FROM DUAL;
		TOTAL:= TOTAL + LINEA.CANTIDAD * PRODUCTO.PVP;
	END LOOP;
	RETURN TOTAL;
	END;
END;
/

--Creación de tablas de objetos
CL SCR;

CREATE TABLE TABLA_CLIENTES OF TIP_CLIENTE(
ID_CLIENTE PRIMARY KEY
);

CREATE TABLE TABLA_PRODUCTOS OF TIP_PRODUCTO(
ID_PRODUCTO PRIMARY KEY
);

CREATE TABLE TABLA_VENTAS OF TIP_VENTA(
ID_VENTA PRIMARY KEY
) NESTED TABLE LINEAS STORE AS TIP_VENTAS;

--INSERTS
CL SCR;

INSERT INTO TABLA_CLIENTES VALUES (1,'LUIS GARCÍA',TIP_DIRECCION
								  (
								  'CALLE LAS FLORES,23',
								  'GUADALAJARA',
								  '82738',
								  'GUADALAJARA'
								  ),
						    '11111111C',
						   TIP_TELEFONOS
						   		 (
						   		 '111111111',
						   		 '222222221'
						   		 ));
						 
INSERT INTO TABLA_CLIENTES VALUES (2,'QUE CHAVAL',TIP_DIRECCION
								  (
								  'CALLE LAS CAOBA,23',
								  'MADRID',
								  '82738',
								  'MADRID'
								  ),
						    '11111112C',
						   TIP_TELEFONOS
						   		 (
						   		 '111111112',
						   		 '222222222'
						  		 ));						   		 

INSERT INTO TABLA_PRODUCTOS VALUES (1,'CAJA DE CRISTAL DE MURANO',100,5);
INSERT INTO TABLA_PRODUCTOS VALUES (2,'BICICLETA',120,15);
INSERT INTO TABLA_PRODUCTOS VALUES (3,'LAPICES',20,5);
INSERT INTO TABLA_PRODUCTOS VALUES (4,'REPRODUCTOR',600,5);
INSERT INTO TABLA_PRODUCTOS VALUES (5,'LAPTOP',400,10);

--TABLA ANIDADA

INSERT INTO TABLA_VENTAS SELECT 1,REF(C),SYSDATE,TIP_LINEAS_VENTA() FROM TABLA_CLIENTES C WHERE C.ID_CLIENTE=1;

INSERT INTO TABLA_VENTAS VALUES(2,(SELECT REF(C) FROM TABLA_CLIENTES C 
WHERE C.ID_CLIENTE=1),SYSDATE, TIP_LINEAS_VENTA(
TIP_LINEA_VENTA(1,(SELECT REF(P) FROM TABLA_PRODUCTOS P WHERE ID_PRODUCTO=1),1),
TIP_LINEA_VENTA(2,(SELECT REF(P) FROM TABLA_PRODUCTOS P WHERE ID_PRODUCTO=2),2)));

INSERT INTO TABLA_VENTAS VALUES(3,(SELECT REF(C) FROM TABLA_CLIENTES C 
WHERE C.ID_CLIENTE=1),SYSDATE, TIP_LINEAS_VENTA(
TIP_LINEA_VENTA(1,(SELECT REF(P) FROM TABLA_PRODUCTOS P WHERE ID_PRODUCTO=1),2),
TIP_LINEA_VENTA(2,(SELECT REF(P) FROM TABLA_PRODUCTOS P WHERE ID_PRODUCTO=2),1),
TIP_LINEA_VENTA(3,(SELECT REF(P) FROM TABLA_PRODUCTOS P WHERE ID_PRODUCTO=3),4)));

--Consultas
CL SCR;

--Consulta 6.1
SELECT DIR.NUMERO_LINEA FROM TABLA_VENTAS X, TABLE(X.LINEAS) DIR WHERE ID_VENTA=2;

--Consulta 6.2
SELECT DIR.NUMERO_LINEA,DEREF(DIR.ID_PRODUCTO) FROM TABLA_VENTAS X, TABLE(X.LINEAS) DIR WHERE ID_VENTA=2;

--Consulta 6.3
SELECT ID_VENTA,DIR.NUMERO_LINEA FROM TABLA_VENTAS X, TABLE(X.LINEAS) DIR;

--Consulta 6.4
SELECT NOMBRE FROM TABLA_CLIENTES WHERE ID_CLIENTE=2;

--Consulta 6.5
UPDATE TABLA_CLIENTES SET NOMBRE='ROSA SERRANO' WHERE ID_CLIENTE=2;

--UPDATE 6.6
UPDATE TABLA_CLIENTES SET DIREC=TIP_DIRECCION('CALLE ESTOPA, 23','MADRID','282888','MADRID') WHERE ID_CLIENTE=2;

--UPDATE 6.7
SELECT * FROM TABLA_CLIENTES  WHERE ID_CLIENTE=1;
UPDATE TABLA_CLIENTES SET TELEF= TIP_TELEFONOS('9284728472','111111112','222222222') WHERE ID_CLIENTE=1;
SELECT VALUE(C) FROM TABLA_CLIENTES C WHERE ID_CLIENTE=1;

--Consulta 6.8
SELECT DEREF(ID_CLIENTE).NOMBRE FROM TABLA_VENTAS X WHERE ID_VENTA=2;

--Consulta 6.9
SELECT DEREF(ID_CLIENTE) FROM TABLA_VENTAS X WHERE ID_VENTA=2;

--Consulta 6.10
DECLARE

	V_TIPVENTA TIP_LINEAS_VENTA;
	
BEGIN
	SELECT LINEAS INTO V_TIPVENTA
	FROM TABLA_VENTAS 
	WHERE DEREF(ID_CLIENTE).ID_CLIENTE=1;
	
	FOR I IN V_TIPVENTA.FIRST .. V_TIPVENTA.LAST LOOP
		
		DBMS_OUTPUT.PUT_LINE('JODER');
		
	END LOOP;

END;
/


--Consulta 6.11
--SELECT DEREF(ID_CLIENTE).NOMBRE,ID_VENTA FROM TABLA_VENTAS X;

--Consulta 6.12


SELECT DEREF(ID_CLIENTE).ID_CLIENTE FROM TABLA_VENTAS WHERE DEREF(ID_CLIENTE).ID_CLIENTE=1 GROUP BY DEREF(ID_CLIENTE).ID_CLIENTE;
















































